variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - upload

build_package:
  stage: build
  cache:
    paths:
      - build/
      - "addon/*/*/build"
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle build
    - ( cd addon/ObjectTrap/PyScript && gradle build )
    - ( cd addon/ObjectTrap/ScalaScript && gradle build )
  tags:
    - java
    - gradle
  except:
    - /^test-.*$/
    - tags

upload_package:
  stage: upload
  cache:
    paths:
      - build/
      - "addon/*/*/build"
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle upload
    - ( cd addon/ObjectTrap/PyScript && gradle upload )
    - ( cd addon/ObjectTrap/ScalaScript && gradle upload )
  tags:
    - java
    - gradle
  only:
    - /^master$/
