before_script:
  - git submodule update --init
  - cp ~/publish.secrets.ZWUtils-Java publish.secrets

stages:
  - build
  - deploy

build_package:
  stage: build
  cache:
    paths:
      - build/
  script:
    - gradle build
  tags:
    - java
    - gradle
  except:
    - /^test-.*$/

deploy_package:
  stage: deploy
  cache:
    paths:
      - build/
  script:
    - gradle upload
  tags:
    - java
    - gradle
  except:
    - /^test-.*$/

