variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: registry.local/builder-jdk8:latest

stages:
  - build
  - publish

build_package:
  stage: build
  cache:
    paths:
      - build/
      - "addon/*/*/build"
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle build
    - ( cd addon/ObjectTrap/PyScript && gradle build )
    - ( cd addon/ObjectTrap/ScalaScript && gradle build )
  tags:
    - java
    - gradle
    - docker-runner
  except:
    - /^test-.*$/
    - /^master$/
    - tags

publish_package:
  stage: publish
  cache:
    paths:
      - build/
      - "addon/*/*/build"
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle upload
    - ( cd addon/ObjectTrap/PyScript && gradle upload )
    - ( cd addon/ObjectTrap/ScalaScript && gradle upload )
  tags:
    - java
    - gradle
    - docker-runner
  only:
    - /^master$/
