before_script:
  - git submodule update --init --recursive
  - set -a && . ~/publish.env.ZWUtils-Java

stages:
  - build
  - deploy

build_package:
  stage: build
  cache:
    paths:
      - build/
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle build
  tags:
    - java
    - gradle
  except:
    - /^test-.*$/
    - /^master$/
    - tags

deploy_package:
  stage: deploy
  cache:
    paths:
      - build/
    key: "$CI_BUILD_REF_NAME"
    untracked: true
  script:
    - gradle upload
  tags:
    - java
    - gradle
  only:
    - /^master$/

